### PR TITLE
Updated to 1.3

### PR DESCRIPTION
**Pull request by TMPhoenix**
Hi,

I took the liberty of making a pull request for this.

It should fix the mod for 1.3.
- fixed the crossblooded icon (I think)
- removed patch that is no longer needed, and renamed GetCaption to GetUIText
- Added a custom BigInteger replacement for the now removed System.Numerics. It covers the use cases you used in the mod, which should maintain backwards compatibility
- renamed TriggerEntity to SourceEntity

Did some testing. I was able to make a new character and load an existing game. No errors as far as I can tell.

### CODE REVIEW

**Comment by TMPhoenix** [comment]
Based on some user reports there are still some issues with the changes, so I'll update this once I figure out what's wrong.

**Comment by darthksurfer** [comment]
@TMPhoenix  If I may ask where do I download the 1.3 file of this

**Comment by TMPhoenix** [comment]
Look at the releases on my fork.

**Comment by darthksurfer** [comment]
I did thank you, I put everything in the mods folder after I zipped it. Is that what I was suppose to do, or what am I suppose to do with all the other folders

**Comment by TMPhoenix** [comment]
Uh, go to the releases tab and download the dll. Replace the old one.

**Pull request closed without merging**
